### ISSUE TITLE
Theoretical Issue

### ISSUE THREAD

**Issue by linhlt-it-ee** [GT-RIPL/L2C#10]
Can you please tell me how you converted [sij=0]P(Yi|xi,theta)*P*Yj|xj,theta) to (1-sij)log(1-f(xi,theta)Tf(fxj,theta))
It seems like P(Yi|xi,theta)*P*Yj|xj,theta) ->1-f(xi,theta)Tf(fxj,theta) for no reason.
It conflicts with the theory when 2 classes are differents. Your loss function has a positive class =1 when 2 samples have the same predictions. It means the higher overlap, the loss should be lower. In your case, the lower of overlap, the loss is lower.

**Comment by yenchanghsu** [comment]
This formula is the result of combining two basic probability operations.
(1) f(xi,theta)Tf(xj,theta): The probability that i and j are from the same class.
(2) 1 - f(xi,theta)Tf(xj,theta): The probability that i and j are NOT from the same class.
Let's look again at the meaning of [sij=0]P(Yi|xi,theta)P(Yj|xj,theta). It means the probability that i and j are NOT from the class. It has the same meaning as (2).
I omitted the notation of summation to align the notation used in your question, but they are important to understand the equations correctly.
I hope this help.

**Comment by linhlt-it-ee** [comment]
by having g= f(xi,theta)Tf(xj,theta) at the end,you interpret this as the Probability 2 samples having the same prediction then your multi-class became binary. But it turns out from the beginning you already assumed that P(Yi|xi,theta)P(Yj|xj,theta)=probability 2 samples having the same prediction? Can you please help me. I really need it to explain why the experiment can be that good for other applications

**Comment by yenchanghsu** [comment]
The notation under the summation specified which type of pair (i,j) is used. The loss for similar pairs (from the same class) and dissimilar pairs (from different classes) are computed separately.
Note that sij is the ground-truth (or pseudo-labeled) pairwise similarity.
f(xi,theta)Tf(xj,theta) is the prediction of of pairwise similarity.
