### ISSUE TITLE
Learning to Cluster for Proposal-Free Instance Segmentation

### ISSUE THREAD

**Issue by msseibel** [GT-RIPL/L2C#2]
Are you going to add the implementation for your instance segmentation approach to this repo, or can I find it somewhere else? 
What kind of Upsampling have you used?

**Comment by yenchanghsu** [comment]
The instance segmentation is implemented during an internship. Due to company policy, it can't be public. I am happy to answer your implementation questions.
The upsampling function is torch.nn.functional.interpolate.
