### ISSUE TITLE
Question about MCL Eq. 1

### ISSUE THREAD

**Issue by WindChimeRan** [GT-RIPL/L2C#3]
In the ICLR2019 paper, the paragraph below Eq. 1, you said that marginalizing Y is intractable and Y_i depends on each other, so the additional independence is introduced. 

Why the computation is intractable and how does Y_i depend on each other?

Eq. 2 is a bit intuitive that I cannot figure out why it is an approximation.

**Comment by yenchanghsu** [comment]
In the graph of figure 2, "Y_i -> S_ij <- Y_j" is a V-structure. Y_i and Y_j depend on each other when S_ij is observed. Due to the dependency, one would need to enumerate all combinations of Y, which makes the computation intractable, to calculate the likelihood exactly.

**Comment by WindChimeRan** [comment]
Thank you! I forgot the V-structure.

**Comment by zycalice** [comment]
I had the same question and thanks for the answer! Could you explain a bit more on how the independent assumption of Sij provides the approximation?
