### ISSUE TITLE
BatchKLdivergence.lua

### ISSUE THREAD

**Issue by absagargupta** [GT-RIPL/L2C#6]
Hello there

Have you also implemented BatchKLdivCriterion.lua in the original code in this repo ?

**Comment by absagargupta** [comment]
And how do you calculate the gradient of the KL divergence loss

**Comment by absagargupta** [comment]
I am sorry I closed the isssue by mistake

**Comment by yenchanghsu** [comment]
This [function](https://github.com/GT-RIPL/L2C/blob/master/modules/criterion.py#L5) is Its equivalent implementation. PyTorch has automatic differentiation, so you don't need to calculate it.

**Comment by yenchanghsu** [comment]
Please feel free to let me know if any questions.
