### ISSUE TITLE
怎么用该算法检测车道线图片数据，代码在哪呢，两个demo的py文件好像都是训练模型的

### ISSUE THREAD

**Issue by yangaiping** [GT-RIPL/L2C#9]
![image](https://user-images.githubusercontent.com/109123962/234882975-01b6cfe5-0025-47d0-b73e-9cce2c3ac55a.png)

**Comment by yenchanghsu** [comment]
This repo does not include the code for lane detection, which was only mentioned as an application example.

**Comment by yangaiping** [comment]
好的谢谢您
